version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: travel-blog-admin
    container_name: travel-blog-admin-app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    depends_on:
      - pgsql

  pgsql:
    image: postgres:15
    container_name: mobile-dashboard-pgsql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
